# Generated by Django 3.1 on 2021-01-07 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GlobalModels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('skills', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(' ', ' '), ('QUICKLEARNER', 'Quick learner'), ('ARTISTIC', 'Artistic skills'), ('TIME_MANAGEMENT', 'Time management'), ('TEAMWORK', 'Teamwork'), ('COMMUNICATION', 'Communication'), ('ENGINEERING', 'Engineering')], max_length=74, null=True)),
                ('field_Of_Work', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(' ', ' '), ('RIGGING', 'Rigging'), ('MODELLING', 'Modeling'), ('VFX', 'Visual effects'), ('TEXTURING', 'Texturing'), ('ANIMATION', 'Animation'), ('FILM', 'Film and Media Arts'), ('GAME_DESIGN', 'Games design'), ('RENDERING', 'Rendering artist'), ('LIGHTNING', 'Lightning artist'), ('BACKGROUND', 'Background artist'), ('GRAPHIC_DESING', 'Graphic design'), ('PRODUCT_DESIGN', 'Product design'), ('CHARACTER_DESIGN', 'Character design'), ('WEBSITE_DESIGNER', '3D website design'), ('INTERACTIVE_DESIGN', 'Interactive design'), ('CHARACTER_ANIMATATION', 'Character Animation')], max_length=196, null=True)),
                ('body_text', models.TextField()),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('number_of_comments', models.IntegerField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('is_remote', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('submition_url', models.CharField(max_length=255)),
                ('experience', models.CharField(blank=True, choices=[('JUNIOR', 'JUNIOR'), ('SENIOR', 'SENIOR'), ('INTERN', 'INTERN'), ('NULL', ' ')], default='', max_length=10)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('location', models.ManyToManyField(blank=True, to='GlobalModels.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Job_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('likes', models.IntegerField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='jobBoard.job')),
            ],
            options={
                'verbose_name_plural': 'Job Comments',
                'ordering': ['pub_date'],
            },
        ),
    ]
