# Generated by Django 3.1 on 2021-02-05 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobBoard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='field_Of_Work',
        ),
        migrations.RemoveField(
            model_name='job',
            name='skills',
        ),
    ]
