# Generated by Django 3.1 on 2021-02-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobBoard', '0002_auto_20210205_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='due_date',
            field=models.DateField(),
        ),
    ]
