# Generated by Django 3.1 on 2021-02-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GlobalModels', '0002_auto_20210107_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
