# Generated by Django 3.1 on 2021-01-20 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210119_1018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='possition',
            new_name='position',
        ),
    ]
