# Generated by Django 3.1 on 2021-02-12 12:33

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210203_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='skills',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(' ', ' '), ('QUICKLEARNER', 'QUICKLEARNER'), ('ARTISTIC', 'ARTISTIC'), ('TIME_MANAGEMENT', 'TIME_MANAGEMENT'), ('TEAMWORK', 'TEAMWORK'), ('COMMUNICATION', 'COMMUNICATION'), ('ENGINEERING', 'ENGINEERING')], default=' ', max_length=74),
        ),
        migrations.AlterField(
            model_name='user',
            name='tools',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(' ', ' '), ('MAX', 'MAX'), ('MAYA', 'MAYA'), ('CINEMA', 'CINEMA'), ('AE', 'AE'), ('PS', 'PS'), ('BLENDER', 'BLENDER'), ('LIGHTWAVE', 'LIGHTWAVE'), ('ZBrush', 'ZBrush')], default=' ', max_length=48),
        ),
        migrations.AlterField(
            model_name='user',
            name='work_fields',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(' ', ' '), ('RIGGING', 'RIGGING'), ('MODELLING', 'MODELLING'), ('VFX', 'VFX'), ('TEXTURING', 'TEXTURING'), ('ANIMATION', 'ANIMATION'), ('FILM', 'FILM'), ('GAME_DESIGN', 'GAME_DESIGN'), ('RENDERING', 'RENDERING'), ('LIGHTNING', 'LIGHTNING'), ('BACKGROUND', 'BACKGROUND'), ('GRAPHIC_DESING', 'GRAPHIC_DESING'), ('PRODUCT_DESIGN', 'PRODUCT_DESIGN'), ('CHARACTER_DESIGN', 'CHARACTER_DESIGN'), ('WEBSITE_DESIGNER', 'WEBSITE_DESIGNER'), ('INTERACTIVE_DESIGN', 'INTERACTIVE_DESIGN'), ('CHARACTER_ANIMATATION', 'CHARACTER_ANIMATATION')], default=' ', max_length=196),
        ),
    ]
