# Generated by Django 3.1 on 2021-02-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='headline_photo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='stories'),
        ),
    ]
